name: NodeJS CI with Matrix, Linting, and Static Analysis

on: push

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]
        environment: [development, staging]
        include:
          - node-version: 20
            environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-eslintfix
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (Static Code Analysis)
        run: npm run lint

      - name: Run tests with output capture
        run: |
          mkdir -p test-output
          npm test | tee test-output/results-${{ matrix.node-version }}-${{ matrix.environment }}.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ matrix.node-version }}-${{ matrix.environment }}
          path: test-output/results-${{ matrix.node-version }}-${{ matrix.environment }}.txt

  deploy-aws:
    needs: build-and-analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install AWS CLI (Official Method)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Deploy to AWS S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        run: |
          echo "Setting up AWS CLI credentials..."
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_REGION"

          echo "Syncing public/ to S3 bucket: $AWS_DEPLOY_BUCKET"
          aws s3 sync ./public s3://$AWS_DEPLOY_BUCKET --delete

          echo "✅ Deployment to AWS S3 completed"
